### ISSUE TITLE
Create symbolic link instead of copying file

### ISSUE THREAD

**Issue by BlakeGFitch** [pieper/dicomsort#14]
This is a feature request.

Could there be an option to create a symbolic link instead of a copy of the file? 

The newly created folder would provide and organized view of the data which remained in place in the old file structure. Multiple views could be created without duplicating data.

**Comment by pieper** [comment]
That's a good idea.  Any chance you'd want to try implementing it?  I don't particularly need this feature but I could review a pull request.

**Comment by BlakeGFitch** [comment]
I tried this by modifying the file copy line to do a link and it works well. I'll have a look at enabling it via a command line arg.
