### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by denbonte** [pieper/dicomsort#19]
Hey Steve,

Thanks again for the work you put in dicomsort.

While running the script in python3, one python2 to 3 compatibility error hit me:

```
python3 dicomsort.py -u $SRC_DIR $DST_DIR/%PatientID/%StudyInstanceUID/%SeriesInstanceUID/%SOPInstanceUID.dcm --deleteSource --keepGoing --verbose

ERROR, UNEXPECTED EXCEPTION
name 'raw_input' is not defined
Traceback (most recent call last):
  File "dicomsort.py", line 500, in <module>
    if confirmDelete(sorter):
  File "dicomsort.py", line 480, in confirmDelete
    response = raw_input ('Delete source directory? [y/N] ')
NameError: name 'raw_input' is not defined
```

In this case, the quick fix would be substituting python2's `raw_input()` with python3's `input()`.
Supposing many users will still be using dicomsort with python2 (and this would break their script), I guess the simplest thing to do would be some binding like:

```
try:
    raw_input = input
except NameError:
    pass
```

or the other way around. If the user has `future` installed, then the following should also work:

```
# import from future
from builtins import input
```

---

### Pylint3

Wondering if there were other potential compatibility issues - and being as lazy as a toad - I ran [pylint3](https://github.com/PyCQA/pylint). Here's the output of `pylint3 dicomsort.py | grep "W:\|E:"`(I separated the errors from the warning for the sake of clarity):

```
W:138, 0: Bad indentation. Found 14 spaces, expected 16 (bad-indentation)
W:139, 0: Bad indentation. Found 16 spaces, expected 20 (bad-indentation)
W:141, 0: Bad indentation. Found 14 spaces, expected 16 (bad-indentation)
W:142, 0: Bad indentation. Found 16 spaces, expected 20 (bad-indentation)
W:143, 0: Bad indentation. Found 14 spaces, expected 16 (bad-indentation)
W:144, 0: Bad indentation. Found 16 spaces, expected 20 (bad-indentation)
W:145, 0: Bad indentation. Found 16 spaces, expected 20 (bad-indentation)
W:146, 0: Bad indentation. Found 16 spaces, expected 20 (bad-indentation)
W:148, 0: Bad indentation. Found 14 spaces, expected 16 (bad-indentation)
W:198,22: Unused variable 'subFolders' (unused-variable)
W:111, 8: Attribute 'options' defined outside __init__ (attribute-defined-outside-init)
W:185, 8: Attribute 'filesRenamed' defined outside __init__ (attribute-defined-outside-init)
W:186, 8: Attribute 'filesSkipped' defined outside __init__ (attribute-defined-outside-init)
W:398,13: Redefining name 'sorter' from outer scope (line 487) (redefined-outer-name)
W:420,12: Unused variable 'root' (unused-variable)
W:420,18: Unused variable 'subFolders' (unused-variable)
W:441,14: Redefining name 'sorter' from outer scope (line 487) (redefined-outer-name)
W:476,18: Redefining name 'sorter' from outer scope (line 487) (redefined-outer-name)
W:510,11: Catching too general exception Exception (broad-except)
W:514, 8: Access to a protected member _exit of a client class (protected-access)
W: 24, 0: Unused import time (unused-import)
```
```
E:344,12: Module 'urllib' has no 'urlretrieve' member (no-member)
E:480,15: Undefined variable 'raw_input' (undefined-variable)
```

Hoping this helps,
Dennis.

**Comment by pieper** [comment]
Ah, yes, thanks so much for the detailed info.  These all look pretty addressable.

My preference at this point would be to focus on python3 since so many packages have deprecated python2 support.  Anyone who needs python2 can just use an older dicomsort from git history.  Sound okay @denbonte ?

**Comment by phcerdan** [comment]
I think this was addressed in https://github.com/pieper/dicomsort/commit/d9eb73806d46efe2760e0d4be546eac91d906210

I have tested python3 in current master 94cae7ab1e07a781aadf58209a72408bca3c8b2e and it works.

Thanks for the package @pieper!
