### ISSUE TITLE
What DICOM tags are available for use?

### ISSUE THREAD

**Issue by aribesik** [pieper/dicomsort#23]
Hi there - I was trying to use the DICOM tag %ProtocolName   (0018,1030)  but it wasn't working to sort the files...

What DICOM tags are available for dicomsort to use? Is there a way to use the actual tags rather than the name of the tag?

**Comment by pieper** [comment]
Any particular dicom file might not have a particular tag.  You can look in the standard for what tags are meant to be there and which are optional, but sometimes files don't match the standard.

I suggest you look at the headers using tool like this one to look at the file headers: https://dicom.innolitics.com. From there you can get the tag names to sort by.

**Comment by aribesik** [comment]
I was able to use AFNI for example to extract information from this particular dataset with this ProtocolName tag, but was not able to use this tag using dicomsort.  So the file has the tag - it just isn't being read by dicomsort for some reason

**Comment by pieper** [comment]
dicomsort uses the names as exposed by pydicom.  Do you know enough python to print them out?  Basically just:
```
>>> import pydicom
>>> ds = pydicom.read_file("/path/to/file.dcm")
>>> print(ds)
```
And you'll see the tags available.  Perhaps it has a different name or it isn't in the pydicom data dictionary.

**Comment by aribesik** [comment]
Thanks a lot for the speedy replies !

I don't have a lot of experience with python no, but I get what's happening in the code you pasted and I'll give this a shot. Thank you!

**Comment by aribesik** [comment]
(0018, 1030) Protocol Name                       LO: 'RES-02-0309-A_HC study_/'

so it is there from this command - since there is a space, do I just put "Protocol Name" in brackets like so for it to work:

%"Protocol Name"

**Comment by pieper** [comment]
Is it nested in a sequence?  I don't think dicomsort supports that.  Otherwise it should work with no space.  E.g. like this:

```
>>> ds.ProtocolName
'Full - Standard dose'
```

What's the actual command line and error message you get?

**Comment by aribesik** [comment]
ahhhhh so sorry to waste your time with this...
it is working! %ProtocolName works (not sure what I did before to mess this up but its working now) 

Thanks again

**Comment by aribesik** [comment]
Hi again - so, I was able to replicate the error I was having before (where I specified the dicom header name properly, but dicomsort behaved as though the header was unknown/didn't exist) and am finding other strange behaviour and am not sure what is going on ... 

In the first screenshot, 
![image](https://user-images.githubusercontent.com/116363796/213255121-e7a4f5fa-02b9-4290-8fcc-9f2cf56394a8.png)

the command containing %SeriesNumber_%SeriesDescription somehow returned unknown for series description. I just added an underscore and suddenly SeriesDescription was recognized as a tag. 
![image](https://user-images.githubusercontent.com/116363796/213256332-af5f59d2-88fe-46d8-a0e1-2e18d9386bbe.png)


So, I guess tags cannot end the command without some sort of extension, which is fair given typically people who aren't troubleshooting like I am will have .dcm as the end of their command so I guess the error shouldn't be thrown. 

But for some reason, dicomsort is only recognizing 3 series numbers - 15, 27, and 57 ;  when I use AFNI's dicom_hinfo command to extract out unique series numbers, there are many more (screenshot truncated. tag 0020,0011 is for series number, the command is basically searching all .dcm files and then counting all the unique series numbers and showing them on the right. Even though it's not counting properly, it does show there are more than 15, 27 and 57 series numbers in this dataset). 
![image](https://user-images.githubusercontent.com/116363796/213256408-bb024110-923b-4e6f-b7fe-0a35fa62e0e3.png)

dcm2niix also spits out many more series numbers. So I am  not sure how to get dicomsort to recognize these other series numbers... I don't know if this is because dicomsort uses a slightly different tag, or what is going on

**Comment by pieper** [comment]
Using the python commands or other dicom dump utility can you check that the files have unique study descriptions and series descriptions?  You may need to look through all the files.  If not then it looks like you are ending up with non-unique output filenames, so dicomsort is refusing to overwrite files that result in the same output pattern.  Sometime research files don't have conventionally formatted headers.

**Comment by aribesik** [comment]
From my understanding... the AFNI command (which is searching through all of the .dcm files and dumping their series number only) is dumping different series numbers, using the SeriesNumber tag, that dicomsort is not detecting, using allegedly the same tag. 

![image](https://user-images.githubusercontent.com/116363796/213260052-cf41cd5c-94a1-407b-8215-fe34159f1612.png)

If I just try to sort by series number, which assuming as AFNI says there are more than 3 unique series numbers, I only get 3 series numbers.  dcm2niix and AFNI both detect more than 3 unique series numbers.

**Comment by pieper** [comment]
The key point is the abort message.  dicomsort is telling you that the pattern you picked results in name clashes in the output so it stops trying to generate the output.

Why don't you try the --verbose and --keepGoing flags and review the output.  This should help you better understand the structure of the data you are working with.  The warning will print where there's a name clash and where there isn't.

**Comment by aribesik** [comment]
ok - I had assumed that it would still sort the first file that matched the command - and then stop copying any files that would overwrite it. instead, if there is any conflict **no files are sorted at all**, which explains why the folders were missing. i understood that I had to be more specific but did not understand why I was having an issue at such a broad level (eg seemingly missing scan numbers). It might be helpful if this is explained more clearly in the documentation (ie that **no files** will be sorted if there is a match conflict for that file and its matches)

thanks again for your help
