### ISSUE TITLE
Zero pad numerical values

### ISSUE THREAD

**Issue by neurolabusc** [pieper/dicomsort#7]
Hello
The script works
  python dicomsort.py /Users/me/unsorted /Users/me/sorted/%SeriesNumber/%InstanceNumber.dcm
but instance numbers are saved 1.dcm,2.dcm,... how does one zero pad the outputs so you get 0001.dcm, 0002.dcm,etc?

**Comment by pieper** [comment]
Unfortunately there's not easy way to do that - the filename components are extracted directly from the dicom values and those are not zero padded.

I'd suggest writing a small script (in python or similar language) that does the renaming of the files after they've been sorted.  Let me know if you want some hints about how to write it.
